eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9004
spring:
  application:
    name: ApiGateway
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: apec
        predicates:
        - Path=/getOffers/**
        uri: APEC-MICROSERVICE/**
        filters:
        - Hystrix=myCommandName
hystrix:
  command:
    myCommandName:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:
              30000

        