eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9004
spring:
  application:
    name: ApiGateway
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: users
        predicates:
        - Path=/users/**
        uri: lb://PHOTOAPPAPI-USERS/users
