eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9004
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n" 
spring:
  application:
    name: ApiGateway
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: offer_route
        uri: http://baeldung.com
        predicates:
        - Path=/offer/
management:
  endpoints:
    web:
      exposure:
        include: "*"  