eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    health-check-url-path: /actuator/health
server:
  port: 9010
spring:
 security:
   user:
    name: utilisateur
    password: Lam@86